// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// koneksi firebase
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF_WR3NYEPq-rNGk6k6KglVit1xWhuJk0',
    appId: '1:163998572071:web:b9ef7a5c72de3b08e47802',
    messagingSenderId: '163998572071',
    projectId: 'smart-medic-89eb7',
    authDomain: 'smart-medic-89eb7.firebaseapp.com',
    storageBucket: 'smart-medic-89eb7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOv8rrI-Weei7xS_tm8KIA8LSryzdDD04',
    appId: '1:163998572071:android:7a32b3b4e31dcafbe47802',
    messagingSenderId: '163998572071',
    projectId: 'smart-medic-89eb7',
    storageBucket: 'smart-medic-89eb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKbjyYoQbTCAn8me_WQ2o-I7bDSjp4XtM',
    appId: '1:163998572071:ios:19c359c2cc7b9fd9e47802',
    messagingSenderId: '163998572071',
    projectId: 'smart-medic-89eb7',
    storageBucket: 'smart-medic-89eb7.appspot.com',
    iosClientId: '163998572071-dqte9shvhitmo13hog3ofmrdflpkl919.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartMedic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKbjyYoQbTCAn8me_WQ2o-I7bDSjp4XtM',
    appId: '1:163998572071:ios:19c359c2cc7b9fd9e47802',
    messagingSenderId: '163998572071',
    projectId: 'smart-medic-89eb7',
    storageBucket: 'smart-medic-89eb7.appspot.com',
    iosClientId: '163998572071-dqte9shvhitmo13hog3ofmrdflpkl919.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartMedic',
  );
}
